# Path: docker-compose.yml
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: storesphere-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: storesphere_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.ddocker-compose up --build -d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: storesphere-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=3306
      - DB_PASSWORD=admin_password
      - DB_NAME=storesphere_db
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: storesphere-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      - backend

volumes:
  mysql_data: